# Python Basics — Complete Fundamentals Guide
A complete beginner-friendly Python reference with explanations, practical examples, and outputs.

The notebook moves from core syntax to concepts commonly used in data analysis.

## 1. Printing, Comments, Variables, and Data Types
Python variables store values without requiring an explicit type declaration. Common types include `str`, `int`, `float`, `bool`, and `NoneType`.

In [1]:
# A comment starts with #
name = 'Samaher'
age = 27
height = 1.65
is_learning = True
missing_value = None
print('Hello, Python!')
print(name, age, height, is_learning, missing_value)
print(type(name), type(age), type(height), type(is_learning), type(missing_value))

Hello, Python!
Samaher 27 1.65 True None
<class 'str'> <class 'int'> <class 'float'> <class 'bool'> <class 'NoneType'>


## 2. Type Conversion
Use `int()`, `float()`, `str()`, and `bool()` to convert between compatible data types.

In [2]:
number_text = '42'
number = int(number_text)
price = float('19.99')
year_text = str(2026)
print(number + 8)
print(price)
print(year_text)

50
19.99
2026


## 3. Operators
Python supports arithmetic, comparison, assignment, logical, identity, and membership operators.

In [3]:
a = 10
b = 3
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a // b)
print(a % b)
print(a ** b)
score = 85
print(score >= 60 and score <= 100)
print('Python' in ['Python', 'SQL', 'Pandas'])

13
7
30
3.3333333333333335
3
1
1000
True
True


## 4. Strings
Strings are ordered sequences of characters. They support indexing, slicing, searching, replacing, splitting, joining, and formatting.

In [4]:
text = 'Python Programming'
print(text[0])
print(text[-1])
print(text[:6])
print(text.upper())
print(text.lower())
print(text.replace('Programming', 'Basics'))
print(len(text))
sentence = 'Python is easy to learn'
words = sentence.split()
print(words)
print('-'.join(words))
print(f'My name is {name} and I am {age} years old.')

P
g
Python
PYTHON PROGRAMMING
python programming
Python Basics
18
['Python', 'is', 'easy', 'to', 'learn']
Python-is-easy-to-learn
My name is Samaher and I am 27 years old.


## 5. Lists
Lists are ordered, mutable collections that can contain duplicates and different data types.

In [5]:
skills = ['Python', 'SQL', 'Machine Learning']
skills.append('Pandas')
skills.insert(1, 'NumPy')
skills.extend(['Matplotlib', 'Git'])
print(skills)
print(skills[0])
print(skills[-1])
skills.remove('Git')
removed = skills.pop()
print('Removed:', removed)
numbers = [5, 2, 8, 1, 3]
numbers.sort()
print(numbers)

['Python', 'NumPy', 'SQL', 'Machine Learning', 'Pandas', 'Matplotlib', 'Git']
Python
Git
Removed: Matplotlib
[1, 2, 3, 5, 8]


## 6. Tuples, Sets, and Dictionaries
Tuples are ordered and immutable. Sets store unique values. Dictionaries store key-value pairs.

In [6]:
coordinates = (10, 20, 30)
x_coord, y_coord, z_coord = coordinates
print(coordinates)
print(x_coord, y_coord, z_coord)
set_a = {1, 2, 3, 3}
set_b = {3, 4, 5}
print(set_a)
print(set_a | set_b)
print(set_a & set_b)
student = {'name': 'Samaher', 'age': 27, 'field': 'Data Science'}
print(student['name'])
print(student.get('field'))
student['city'] = 'Riyadh'
for key, value in student.items():
    print(key, ':', value)

(10, 20, 30)
10 20 30
{1, 2, 3}
{1, 2, 3, 4, 5}
{3}
Samaher
Data Science
name : Samaher
age : 27
field : Data Science
city : Riyadh


## 7. Conditional Statements
`if`, `elif`, and `else` let a program make decisions. A conditional expression provides a short one-line alternative for simple cases.

In [7]:
score = 92
if score >= 90:
    grade = 'A'
elif score >= 80:
    grade = 'B'
elif score >= 70:
    grade = 'C'
else:
    grade = 'Needs Improvement'
print(grade)
status = 'Adult' if age >= 18 else 'Minor'
print(status)

A
Adult


## 8. Loops, `break`, and `continue`
A `for` loop iterates over items. A `while` loop repeats while a condition remains true. `break` stops a loop and `continue` skips the current iteration.

In [8]:
for number in range(1, 6):
    print(number)
count = 1
while count <= 3:
    print('Count:', count)
    count += 1
for number in range(1, 8):
    if number == 3:
        continue
    if number == 6:
        break
    print('Loop:', number)

1
2
3
4
5
Count: 1
Count: 2
Count: 3
Loop: 1
Loop: 2
Loop: 4
Loop: 5


## 9. `enumerate()` and `zip()`
`enumerate()` returns an index with each item. `zip()` combines values from multiple iterables.

In [9]:
skills = ['Python', 'SQL', 'Pandas']
for index, skill in enumerate(skills, start=1):
    print(index, skill)
names = ['Sara', 'Nora', 'Layan']
scores = [90, 88, 95]
for student_name, student_score in zip(names, scores):
    print(student_name, student_score)

1 Python
2 SQL
3 Pandas
Sara 90
Nora 88
Layan 95


## 10. Functions
Functions organize reusable code. Python supports positional arguments, keyword arguments, default values, `*args`, and `**kwargs`.

In [10]:
def greet(name):
    return f'Hello, {name}!'
def introduce(name, field='Data Science'):
    return f'{name} studies {field}.'
def total(*numbers):
    return sum(numbers)
def show_profile(**info):
    for key, value in info.items():
        print(key, value)
print(greet('Samaher'))
print(introduce('Samaher'))
print(introduce(field='AI', name='Samaher'))
print(total(1, 2, 3, 4, 5))
show_profile(name='Samaher', age=27, field='Data Science')

Hello, Samaher!
Samaher studies Data Science.
Samaher studies AI.
15
name Samaher
age 27
field Data Science


## 11. Scope
Variables created inside a function are local. Variables defined outside functions are usually global.

In [11]:
global_value = 100
def scope_example():
    local_value = 50
    print('Local:', local_value)
    print('Global:', global_value)
scope_example()

Local: 50
Global: 100


## 12. Lambda, `map()`, `filter()`, and `sorted()`
Lambda expressions create small anonymous functions. `map()` transforms items, `filter()` selects items, and `sorted()` returns a sorted copy.

In [12]:
numbers = [1, 2, 3, 4, 5]
square = lambda number: number ** 2
squared = list(map(square, numbers))
even_numbers = list(filter(lambda n: n % 2 == 0, numbers))
descending = sorted(numbers, reverse=True)
print(squared)
print(even_numbers)
print(descending)

[1, 4, 9, 16, 25]
[2, 4]
[5, 4, 3, 2, 1]


## 13. Comprehensions
Comprehensions provide a concise syntax for building lists, sets, and dictionaries.

In [13]:
squares = [n ** 2 for n in range(1, 6)]
evens = [n for n in range(10) if n % 2 == 0]
square_lookup = {n: n ** 2 for n in range(1, 6)}
print(squares)
print(evens)
print(square_lookup)

[1, 4, 9, 16, 25]
[0, 2, 4, 6, 8]
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


## 14. Exception Handling
Use `try`, `except`, `else`, and `finally` to handle errors. `raise` lets you deliberately create an exception when a rule is violated.

In [14]:
try:
    value = int('25')
    result = 100 / value
except ValueError:
    print('Invalid number')
except ZeroDivisionError:
    print('Cannot divide by zero')
else:
    print('Result:', result)
finally:
    print('Finished')
def set_age(value):
    if value < 0:
        raise ValueError('Age cannot be negative')
    return value
print(set_age(27))

Result: 4.0
Finished
27


## 15. File Handling
Use `with open(...)` to work with files safely. Common modes are `r` for read, `w` for write, `a` for append, and `x` for create.

In [15]:
with open('example.txt', 'w', encoding='utf-8') as file:
    file.write('Python is easy to read.\n')
    file.write('This is a second line.')
with open('example.txt', 'r', encoding='utf-8') as file:
    content = file.read()
print(content)

Python is easy to read.
This is a second line.


## 16. JSON
The built-in `json` module converts between Python objects and JSON text.

In [16]:
import json
profile = {'name': 'Samaher', 'age': 27, 'field': 'Data Science'}
json_text = json.dumps(profile, indent=2)
print(json_text)
restored_profile = json.loads(json_text)
print(restored_profile['name'])

{
  "name": "Samaher",
  "age": 27,
  "field": "Data Science"
}
Samaher


## 17. Modules and Useful Built-ins
Python's standard library contains many useful modules. Built-ins such as `len`, `sum`, `min`, `max`, `round`, and `abs` require no import.

In [17]:
import math
from statistics import mean
values = [4, 8, 2, 10]
print(math.sqrt(81))
print(mean(values))
print(len(values))
print(sum(values))
print(min(values))
print(max(values))
print(round(3.14159, 2))
print(abs(-10))

9.0
6
4
24
2
10
3.14
10


## 18. Iterators and Generators
An iterator returns one item at a time. Generators use `yield` and are memory-efficient for producing sequences.

In [18]:
items = ['Python', 'SQL', 'Pandas']
iterator = iter(items)
print(next(iterator))
print(next(iterator))
def countdown(number):
    while number > 0:
        yield number
        number -= 1
print(list(countdown(3)))

Python
SQL
[3, 2, 1]


## 19. Object-Oriented Programming (OOP)
A class is a blueprint for objects. `__init__` initializes attributes and methods define object behavior.

In [19]:
class Student:
    def __init__(self, name, field):
        self.name = name
        self.field = field
    def introduce(self):
        return f'{self.name} studies {self.field}.'
student_object = Student('Samaher', 'Data Science')
print(student_object.name)
print(student_object.introduce())

Samaher
Samaher studies Data Science.


## 20. Inheritance and Dataclasses
Inheritance lets one class reuse another class. `@dataclass` simplifies classes used mainly to store data.

In [20]:
from dataclasses import dataclass
class Person:
    def __init__(self, name):
        self.name = name
    def introduce(self):
        return f'I am {self.name}.'
class DataScientist(Person):
    def role(self):
        return 'Builds data-driven solutions.'
person = DataScientist('Samaher')
print(person.introduce())
print(person.role())
@dataclass
class Course:
    name: str
    hours: int
course = Course('Python', 20)
print(course)

I am Samaher.
Builds data-driven solutions.
Course(name='Python', hours=20)


## 21. Regular Expressions
The `re` module is used for pattern matching, searching, validation, and text extraction.

In [21]:
import re
contact_text = 'Contact: student@example.com'
email_match = re.search(r'[\w.-]+@[\w.-]+', contact_text)
if email_match:
    print(email_match.group())

student@example.com


## 22. Date, Time, and Random Values
`datetime` works with dates and time differences. `random` generates pseudo-random values.

In [22]:
from datetime import date, timedelta
import random
sample_date = date(2026, 8, 30)
print(sample_date)
print(sample_date.year)
print(sample_date + timedelta(days=7))
random.seed(42)
print(random.randint(1, 10))
print(random.choice(['Python', 'SQL', 'R']))

2026-08-30
2026
2026-09-06
2
Python


## 23. NumPy Basics
NumPy provides fast arrays, vectorized numerical operations, reshaping, aggregation, and Boolean filtering.

In [23]:
import numpy as np
array = np.array([1, 2, 3, 4, 5])
print(array)
print(array * 2)
print('Mean:', array.mean())
print('Sum:', array.sum())
print('Shape:', array.shape)
matrix = np.array([[1, 2], [3, 4], [5, 6]])
print(matrix.shape)
print(matrix.reshape(2, 3))
print(array[array > 2])

[1 2 3 4 5]
[ 2  4  6  8 10]
Mean: 3.0
Sum: 15
Shape: (5,)
(3, 2)
[[1 2 3]
 [4 5 6]]
[3 4 5]


## 24. pandas Basics
pandas is widely used for structured and tabular data. A `DataFrame` stores data in rows and columns and supports filtering, sorting, grouping, missing-value handling, and much more.

In [24]:
import pandas as pd
student_data = {'Name': ['Samaher', 'Sara', 'Nora', 'Layan'], 'Score': [95, 88, 91, 77], 'Passed': [True, True, True, True]}
df = pd.DataFrame(student_data)
print(df)
print('\nHigh scores:')
print(df[df['Score'] >= 90])
df['Grade'] = ['A', 'B', 'A', 'C']
print('\nAverage score by grade:')
print(df.groupby('Grade')['Score'].mean())

      Name  Score  Passed
0  Samaher     95    True
1     Sara     88    True
2     Nora     91    True
3    Layan     77    True

High scores:
      Name  Score  Passed
0  Samaher     95    True
2     Nora     91    True

Average score by grade:
Grade
A    93.0
B    88.0
C    77.0
Name: Score, dtype: float64


## 25. Python Style and Best Practices
- Use meaningful variable and function names.
- Use `snake_case` for variables and functions.
- Use `PascalCase` for classes.
- Use four spaces for indentation.
- Keep functions focused on one responsibility.
- Avoid duplicated code.
- Add docstrings to important functions and classes.
- Prefer readable code over overly clever code.

In [25]:
def calculate_average(values):
    """Return the arithmetic mean of a non-empty sequence."""
    return sum(values) / len(values)
print(calculate_average([90, 85, 95]))

90.0


## 26. Virtual Environments and `pip`
These commands are normally run in a terminal:

```bash
python -m venv .venv
source .venv/bin/activate        # macOS / Linux
.venv\Scripts\activate         # Windows
pip install pandas
pip freeze > requirements.txt
pip install -r requirements.txt
```

A virtual environment keeps project dependencies isolated.

## 27. Mini Practice Project
This example combines lists, dictionaries, functions, loops, conditions, comprehensions, and aggregation.

In [26]:
students = [
    {'name': 'Sara', 'score': 84},
    {'name': 'Nora', 'score': 56},
    {'name': 'Layan', 'score': 93}
]
def classify(score):
    return 'Pass' if score >= 60 else 'Fail'
for student_record in students:
    result = classify(student_record['score'])
    print(student_record['name'], student_record['score'], result)
average_score = sum(student['score'] for student in students) / len(students)
print('Average:', round(average_score, 2))

Sara 84 Pass
Nora 56 Fail
Layan 93 Pass
Average: 77.67


## Key Takeaways
- Python has readable syntax and a large standard library.
- Variables, collections, operators, conditions, and loops form the core foundation.
- Functions make code reusable and easier to maintain.
- Exceptions and file handling help build more reliable programs.
- OOP organizes related data and behavior into classes.
- NumPy and pandas are key foundations for data analysis.
- Regular practice with small projects is the best way to strengthen Python skills.